### ISSUE TITLE
[TASK] Brain storm needed regarding target and source in git - Deploy.js

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#134] opened 2022-10-06 15:49 UTC
**Question:** What should we do on master git branch when running deploy?

- [ ] Update the source;
- [ ] Update the target;
- [ ] Update both;

**Comment by JoernBerkefeld** [comment] 2022-10-07 14:51
Duplicate of #130

**Closed by JoernBerkefeld** 2022-10-07 14:51 UTC
Labels: chore
