### ISSUE TITLE
[BUG] Cannot deploy importFile when among other files

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#244] opened 2022-10-25 12:04 UTC
**Current Behavior**
  
We can deploy importFile if we try to deploy it alone, but when we try to deploy it among other files it cannot do it.

On commit all went well, but when deploying the importFile file wasn't deployed to target as we can see in the log excerpt I put in this message

**Results link:**
https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003Fax1AAC/view

**Errors in log**
...
11:41:45 : ☇ skipping importFile copado-import / copado-import: Dependent dataExtension with CustomerKey='undefined' was not found on your BU
...
11:41:45 ❌ Deploy failed: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.
11:41:47 CopadoFunction INFO setting status 'Error' error='Deploy failed: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.'
...
11:41:56 CopadoFunction INFO setting status 'Attached mcdev logs'
11:41:56 /tmp/cf_function.sh:1081
11:41:56 throw new Error(
11:41:56 ^
11:41:56 Error: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.
11:41:56 at Function.deployBU (/tmp/cf_function.sh:1081:19)
11:41:56 at async run (/tmp/cf_function.sh:250:13)

**Showing which data were deployed in log**
11:41:42 : Deploying: script
11:41:43 : - updated script: copado-script / copado-script
11:41:43 : script upsert: 0 of 0 created / 1 of 1 updated
11:41:43 : Deploying: dataExtension
11:41:43 : - Caching dependent Metadata: dataExtensionField
11:41:43 : - Please note that Data Retention Policies can only be set during creation, not during update.
11:41:44 : - updated dataExtension: Daniel Ventura / Daniel Ventura
11:41:44 : dataExtension upsert: 0 of 0 created / 1 of 1 updated
11:41:44 : Deploying: dataExtract
11:41:45 : - updated dataExtract: copado-extract / copado-extract
11:41:45 : dataExtract upsert: 0 of 0 created / 1 of 1 updated
11:41:45 : Deploying: fileTransfer
11:41:45 : - updated fileTransfer: copado-filetransfer / copado-filetransfer
11:41:45 : fileTransfer upsert: 0 of 0 created / 1 of 1 updated
11:41:45 : Deploying: importFile
11:41:45 : ☇ skipping importFile copado-import / copado-import: Dependent dataExtension with CustomerKey='undefined' was not found on your BU
11:41:45 : importFile upsert: 0 of 0 created / 0 of 1 updated
11:41:45 : Deploying: automation
11:41:45 : - updated automation: Barcelona Automation / Barcelona Automation
11:41:45 : automation upsert: 0 of 0 created / 1 of 1 updated
11:41:45 : - scheduled automation 'Barcelona Automation' deployed Paused

**Comment by JoernBerkefeld** [comment] 2022-10-26 09:03
root cause was that the improt file activity in our promotion / feature branch did not have a resolvable DE set.
solution worked on in https://github.com/Accenture/sfmc-devtools/issues/479

**Comment by JoernBerkefeld** [comment] 2022-10-26 11:35
closed via PR https://github.com/Accenture/sfmc-devtools/pull/480

**Comment by DannyCastroVentura** [comment] 2022-10-27 16:52
Seems like this is still open: 

https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FbBJAA0/view

Tried to deploy a dataExtension, an automation, an asset and an importFile, the importFile wasn't deployed.

**Logs:**

...
16:46:25	16:46:25 [32minfo[39m: Deploying: folder
16:46:25	16:46:25 [32minfo[39m: folder upsert: 0 created / 0 updated / 1 filtered
16:46:25	16:46:25 [32minfo[39m: Deploying: asset
16:46:25	16:46:25 [32minfo[39m:  - updated asset: copado-sms-518005426 / copado-sms
16:46:25	16:46:25 [32minfo[39m: asset upsert: 0 of 0 created / 1 of 1 updated
16:46:25	16:46:25 [32minfo[39m: Deploying: dataExtension
16:46:25	16:46:25 [32minfo[39m:  - Caching dependent Metadata: dataExtensionField
16:46:26	16:46:26 [32minfo[39m:  - Please note that Data Retention Policies can only be set during creation, not during update.
16:46:26	16:46:26 [32minfo[39m:  - updated dataExtension: Daniel Ventura /  Daniel Ventura
16:46:26	16:46:26 [32minfo[39m: dataExtension upsert: 0 of 0 created / 1 of 1 updated
16:46:26	16:46:26 [32minfo[39m: Deploying: importFile
16:46:26	16:46:26 [31merror[39m:  ☇ skipping importFile copado-import / copado-import: Import Destination DataExtension not defined
16:46:26	16:46:26 [32minfo[39m: importFile upsert: 0 of 0 created / 0 of 1 updated
16:46:26	16:46:26 [32minfo[39m: Deploying: automation
16:46:27	16:46:27 [32minfo[39m:  - updated automation: Barcelona Automation / Barcelona Automation
16:46:27	16:46:27 [32minfo[39m: automation upsert: 0 of 0 created / 1 of 1 updated
16:46:27	16:46:27 [33mwarn[39m:  - scheduled automation 'Barcelona Automation' deployed Paused
16:46:27	16:46:27 [32minfo[39m: 
16:46:27	               :: Deployed 1 BUs
16:46:27	❌ Deploy failed: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.
16:46:28	CopadoFunction INFO setting status 'Error' error='Deploy failed: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.'
16:46:28	DEBUG: Getting mcdev logs
16:46:28	DEBUG: - 2022-10-27T16.45.58.172Z-errors.log
16:46:28	DEBUG: ⚡ copado --uploadfile "logs/2022-10-27T16.45.58.172Z-errors.log"
16:46:28	DEBUG: - 2022-10-27T16.45.58.172Z.log
16:46:28	DEBUG: ⚡ copado --uploadfile "logs/2022-10-27T16.45.58.172Z.log"
16:46:28	DEBUG: Attached mcdev logs
16:46:28	/tmp/cf_function.sh:1193
16:46:28	            throw new Error(
16:46:28	                  ^
16:46:28	Error: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.
16:46:28	    at Function.deployBU (/tmp/cf_function.sh:1193:19)
16:46:28	    at async run (/tmp/cf_function.sh:254:34)

**Closed** 2022-10-27 16:55 UTC
Labels: bug, mcdev, triaged
