### ISSUE TITLE
[BUG] Error on deploy ImportFile

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#222] opened 2022-10-21 12:26 UTC
**Current Behavior**

If deploying a importFile alone, it work:
-

  https://copadonull71743980.lightning.force.com/lightning/r/copado__Promotion__c/a0t09000000llXIAAY/view
![image](https://user-images.githubusercontent.com/72609808/197194919-875d80dd-9841-4a34-8711-d97649c75d56.png)

if deploying an importFile with other things, it dont work:
-

Tried to deploy dataExtension, automation, filetrasnfer, script, dataExtract and importFile -> didn't work:

https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FajXAAS/view
![image](https://user-images.githubusercontent.com/72609808/197194667-b0feda0a-984e-4384-85f3-51ee9ac1d621.png)

**Comment by DannyCastroVentura** [comment] 2022-10-21 12:42
Tried to do it with only a dataExtension and the importFile and still didnt work:

https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FajmAAC/view
![image](https://user-images.githubusercontent.com/72609808/197198250-cd36c12c-28f1-4df7-8ea6-e81532cf1525.png)

**Comment by JoernBerkefeld** [comment] 2022-10-21 13:18
The line from the logs reading ... skipping... is the important one.

The import file definition is incomplete- it does not have a dataextension as target set it seems - based on the logs

**Comment by JoernBerkefeld** [comment] 2022-10-21 13:19
Potentially invalid bug? Need to confirm this in SFMC

**Comment by JoernBerkefeld** [comment] 2022-10-26 09:20
duplicate of #244

**Closed by JoernBerkefeld** 2022-10-26 09:20 UTC
Labels: bug
