### ISSUE TITLE
[BUG] Nothing to commit on deploy assets

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#255] opened 2022-10-26 14:03 UTC
**Current Behavior**
  
On deploying, it says it has nothing to commit, and don't throw any error, so any person which sees that, would think that deploy did succed.

![image](https://user-images.githubusercontent.com/72609808/198046506-1ac04d1e-a43f-4c8f-a09d-0ecc49e26676.png)

**Result link:**
https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003Fb4iAAC/view

**Expected Behavior**
  
- Throw a error if nothing to commit
- Deploy the changes, once we are in deploy, it means it surely have some changes to commit.

**Log**  
...
13:52:28	Retrieve components
13:52:28	===================
13:52:28	DEBUG: replacing market values
13:52:28	typeKeyMap { 'asset-block': [ 'copado-text' ] }
13:52:28	typeArr [ 'asset-block' ]
13:52:28	13:52:28 [32minfo[39m: mcdev:: Retrieve
13:52:28	13:52:28 [32minfo[39m: 
13:52:28	               :: Retrieving Copado-MarkClDevOps/MCDEV_Training_Pre-Target
13:52:28	13:52:28 [32minfo[39m: Caching dependent Metadata: folder
13:52:29	13:52:29 [32minfo[39m: Retrieving: asset-block [2m(Keys: copado-text)[0m
13:52:29	13:52:29 [32minfo[39m: - Retrieving Subtype: block
13:52:29	13:52:29 [32minfo[39m:   Downloaded asset-block: 0
13:52:29	13:52:29 [32minfo[39m: Downloaded: asset (0)
13:52:29	13:52:29 [32minfo[39m: :: Done
13:52:29	13:52:29 [32minfo[39m: mcdev:: getFilesToCommit
13:52:29	fileArr []
13:52:29	Add components in metadata JSON to Git history
13:52:29	===================
13:52:29	Commit
13:52:29	===================
13:52:29	DEBUG: Git diff ended with the result:
13:52:29	DEBUG: []
13:52:29	❌ Nothing to commit as all selected components have the same content as already exists in Git.
13:52:30	CopadoFunction INFO setting status 'Nothing to commit' error='Nothing to commit as all selected components have the same content as already exists in Git.'
13:52:30	❌ git commit failed:Nothing to commit
13:52:31	CopadoFunction INFO setting status 'Error' error='git commit failed:Nothing to commit'
13:52:31	⚠ Failed deploy verification, check BU on SFMC to verify manually. Git not updated with the changes on target BU: Nothing to commit
...
  
  
  
**Additional comments**
  
As we can see in the logs above, it is not downloading the files, and so, nothing to commit.

**Comment by JoernBerkefeld** [comment] 2022-10-28 08:01
Duplicate of #242

**Closed by JoernBerkefeld** 2022-10-28 08:01 UTC
Labels: bug
